require:
  - ./lib/rubocop/formatter/gitlab_formatter

AllCops:
  NewCops: enable

Metrics/BlockLength:
  IgnoredMethods: ['describe']

Naming/FileName:
  Exclude:
    - lib/rubocop-gitlab_formatter.rb
